DROP TABLE IF EXISTS MAIN_${ENV}.JOB_APPLICATION ;

CREATE TABLE MAIN_${ENV}.JOB_APPLICATION (
    ApplicationDate DATE,
    Company VARCHAR(255),
    Job VARCHAR(255),
    Status VARCHAR(55),
    LastChecked DATE
)  ENGINE=INNODB;